# Generated by Django 4.1.7 on 2023-03-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Unassigned', 'Unassigned')], default='Unassigned', max_length=15, null=True),
        ),
    ]
